try installing fafbseg earlier as it is missing later
This is the error message:

** testing if installed package can be loaded from temporary location
Error: package or namespace load failed for ‘malevnc’:
 .onLoad failed in loadNamespace() for 'malevnc', details:
  call: loadNamespace(x)
  error: there is no package called ‘fafbseg’